채널 API
njsh4261/SGS_Last_Punch pull request #96
Opened 2022-01-19 17:06 UTC by chahtk

- 채널 생성 UI & API
- 채널 조회 API

2022-01-19 17:09 UTC, chahtk commented
지효님. 혹시 채널리스트는 앞에서부터 무조건 5개만 조회 되는건가요?

2022-01-19 19:08 UTC, njsh4261 commented
> 지효님. 혹시 채널리스트는 앞에서부터 무조건 5개만 조회 되는건가요?

아뇨, 멤버 목록, 채널 목록, 워크스페이스 목록 등은 페이지네이션이 적용된 결과입니다. URL parameter로 page 번호과 size를 넘기면 원하는 페이지를 조회할 수 있습니다. [워크스페이스 API 문서](https://github.com/njsh4261/SGS_Last_Punch/blob/dev/docs/API_references/backend_workspace_apis.md)를 참조해 주세요. 현재는 API에 default page size를 5로 지정해 두어서 리스트 항목이 5개 이하로만 조회될 수 있습니다.

2022-01-19 19:29 UTC, njsh4261 requested changes
다른 큰 문제는 없지만 #97의 DTO 변경사항으로 인해 코드가 의도대로 동작하지 않을 수 있습니다. 그 부분 고려해주셔야 할 것 같아서 Request changes로 리뷰 드리겠습니다. request/response 포맷 관해서 의견 있으시면 언제든 말씀해 주세요!

2022-01-19 19:29 UTC, njsh4261 commented on src/frontend/web/src/Api/channel.ts
> +interface ICreate {
#97 PR이 merge되면 채널/워크스페이스를 생성시에 보내는 json 포맷이 수정시에 보내는 포맷과 달라질 예정입니다(관련 DTO 리팩토링). 해당 API 문서를 업데이트 해두겠습니다. 참고해 주세요.

2022-01-19 19:29 UTC, njsh4261 commented on src/frontend/web/src/Api/channel.ts
> +    const response = await axios.post(HOST + endpoint, data);
여기서도 마찬가지, #97 PR merge 이후에는 기존과 달리 response body에 새롭게 생성된 채널/워크스페이스의 정보가 담길 예정입니다. 이건 위와 달리 꼭 코드를 변경하셔야 할 필요는 없고 해당 정보를 어떻게 활용할지는 자유롭게 해주시면 되겠습니다. 만약 정보가 필요없다면 말씀주시면 response body에서 제거하겠습니다.

2022-01-19 19:29 UTC, njsh4261 commented on src/frontend/web/src/modules/worksapce.ts
> -import { NavigateFunction } from 'react-router-dom';
파일명에 오타가 있습니다!

2022-01-19 19:29 UTC, njsh4261 commented on src/frontend/web/types/channel.type.ts
> +  workspaceId: number;
백엔드에서 채널이 소속된 워크스페이스도 id 필드가 아닌 채널이 소속된 워크스페이스의 이름, 설명 등의 정보가 담긴 DTO로 넘겨주도록 수정했는데, 그렇게 많은 정보는 필요 없을까요?

2022-01-20 02:26 UTC, njsh4261 approved these changes
LGTM!

2022-01-20 02:26 UTC, merged